# use minimal Travis build image so that we could install our own JDK (Graal) and Maven
# use newest available minimal distro - see https://docs.travis-ci.com/user/languages/minimal-and-generic/
dist: bionic
language: minimal

services:
  - docker

jobs:
  include:
    - script:
        # Login into Heroku Container Registry first, so that we can push our Image later
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com

        # Compile App with Docker
        - docker build . --tag=registry.heroku.com/codenjoyplay/web

        # Push to Heroku Container Registry
        - docker push registry.heroku.com/codenjoyplay/web

        # Give execute permission
        - chmod +x ./heroku-release.sh

        # Release Dockerized Native Spring Boot App on Heroku
        - ./heroku-release.sh codenjoyplay

        # Push to Docker Hub also, since automatic Builds there don't have anough RAM to do a docker build
        - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        - docker tag registry.heroku.com/codenjoyplay/web rajeevmarrapu/codenjoyplay:latest
        - docker push rajeevmarrapu/codenjoyplay:latest

      name: "Native Image compile in Docker on Travis & Push to Heroku Container Registry"