FROM java_workspace
MAINTAINER Alexander Baglay <apofig@gmail.com>

VOLUME /tmp

ARG WAR_FILE
ARG SPRING_PROFILES=sqlite
ARG CONTEXT=codenjoy-contest

COPY ${WAR_FILE} server.war

ENTRYPOINT ["java","-jar","/server.war","--spring.profiles.active=${SPRING_PROFILES}","--context=${CONTEXT}"]