package com.codenjoy.dojo.expansion.model.replay;

/*-
 * #%L
 * expansion - it's a dojo-like platform from developers to developers.
 * %%
 * Copyright (C) 2016 - 2020 Codenjoy
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */


import com.codenjoy.dojo.utils.JsonUtils;
import com.codenjoy.dojo.expansion.services.SettingsWrapper;
import org.json.JSONObject;
import org.junit.Ignore;
import org.junit.Test;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.util.*;

import static java.util.stream.Collectors.toList;
import static org.junit.Assert.*;

/**
 * Created by Oleksandr_Baglai on 2017-09-21.
 */
public class LoggerReaderTest {

    private static final String REPLAY =
            "                    " +
            "                    " +
            "   OOO  OOOO OOO    " +
            "   O  O O    O  O   " +
            "   O  O O    O  O   " +
            "   OOO  OOO  OOO    " +
            "   OO   O    O      " +
            "   O O  O    O      " +
            "   O  O OOOO O      " +
            "                    " +
            "                    " +
            "    O     OO  O  O  " +
            "    O    O  O O  O  " +
            "    O    O  O O  O  " +
            "    O    OOOO  OOO  " +
            "    O    O  O    O  " +
            "    O    O  O   O   " +
            "    OOOO O  O OO    " +
            "                    " +
            "                    ";

    private static final String SEP = FileSystems.getDefault().getSeparator();

    @Test
    public void testParseFile() throws IOException {
        // given
        SettingsWrapper.setup().roundTicks(50);

        String data = "Game started\n" +
                "New player P@53ff5eb9 registered with hero H@14fa45c2 with base at '{\"x\":5,\"y\":12}' and color '0' for user 'demo1@codenjoy.com'\n" +
                "// please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo1@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@53ff5eb9'}\"\n" +

                "New player P@76fd46ad registered with hero H@59fdaa77 with base at '{\"x\":13,\"y\":13}' and color '1' for user 'demo2@codenjoy.com'\n" +
                "// please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo2@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@76fd46ad'}\"\n" +

                "New player P@310933ee registered with hero H@149c14b4 with base at '{\"x\":14,\"y\":7}' and color '2' for user 'demo3@codenjoy.com'\n" +
                "// please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo3@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@310933ee'}\"\n" +

                "New player P@4fe98a9c registered with hero H@5bc68d76 with base at '{\"x\":6,\"y\":6}' and color '3' for user 'demo4@codenjoy.com'\n" +
                "// please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo4@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@4fe98a9c'}\"\n" +

                "Hero H@14fa45c2 of player P@53ff5eb9 received command:'{\"increase\":[{\"count\":10,\"region\":{\"x\":5,\"y\":12}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":5,\"y\":12}},{\"count\":7,\"direction\":\"DOWN\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":6,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":12}}]}'\n" +
                "Hero H@59fdaa77 of player P@76fd46ad received command:'{\"increase\":[{\"count\":10,\"region\":{\"x\":13,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":11,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":13}}]}'\n" +
                "Hero H@149c14b4 of player P@310933ee received command:'{\"increase\":[{\"count\":10,\"region\":{\"x\":14,\"y\":7}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"LEFT_UP\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"UP\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":7}}]}'\n" +
                "Hero H@5bc68d76 of player P@4fe98a9c received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":2,\"region\":{\"x\":6,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":9,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}}]}'\n" +
                "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"-------------------------------------------------------------------------------------------------------------------------------------♦-----------♥------------------------------------------------------------------------------------------------------------♣-----------♠-------------------------------------------------------------------------------------------------------------------------------------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
                "--------------------------------------------------------------\n" +
                "Hero H@14fa45c2 of player P@53ff5eb9 received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"region\":{\"x\":4,\"y\":12}},{\"count\":3,\"region\":{\"x\":4,\"y\":13}},{\"count\":0,\"region\":{\"x\":5,\"y\":11}},{\"count\":1,\"region\":{\"x\":5,\"y\":13}},{\"count\":2,\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"region\":{\"x\":6,\"y\":12}},{\"count\":1,\"region\":{\"x\":6,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":11}},{\"count\":2,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":5,\"y\":11}},{\"count\":5,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":13}}]}'\n" +
                "Hero H@59fdaa77 of player P@76fd46ad received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":13,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":13}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":8,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":12}}]}'\n" +
                "Hero H@149c14b4 of player P@310933ee received command:'{\"increase\":[{\"count\":2,\"region\":{\"x\":13,\"y\":6}},{\"count\":2,\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"region\":{\"x\":15,\"y\":8}},{\"count\":1,\"region\":{\"x\":15,\"y\":7}},{\"count\":1,\"region\":{\"x\":13,\"y\":8}},{\"count\":1,\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"region\":{\"x\":13,\"y\":7}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":13,\"y\":8}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":8}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":6}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":14,\"y\":8}}]}'\n" +
                "Hero H@5bc68d76 of player P@4fe98a9c received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":6,\"y\":5}},{\"count\":0,\"region\":{\"x\":5,\"y\":5}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":6,\"y\":5}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":9,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":7}}]}'\n" +
                "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#00C001001-=#-=#-=#-=#-=#-=#-=#-=#-=#006007001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#002003002-=#-=#-=#-=#-=#-=#-=#-=#-=#00100100A-=#-=#-=#-=#-=#002001002-=#-=#-=#-=#-=#-=#-=#-=#-=#001003001-=#-=#-=#-=#-=#003002003-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"----------------------------------------------------------------------------------------------------------------♦♦♦---------♥♥♥-----♦♦♦---------♥♥♥-----♦♦♦---------♥♥♥------------------------------------------------------------------♣♣♣---------♠♠♠-----♣♣♣---------♠♠♠-----♣♣♣---------♠♠♠----------------------------------------------------------------------------------------------------------------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
                "--------------------------------------------------------------\n" +
                "Hero H@14fa45c2 of player P@53ff5eb9 received command:'{\"increase\":[{\"count\":2,\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"region\":{\"x\":3,\"y\":11}},{\"count\":1,\"region\":{\"x\":3,\"y\":12}},{\"count\":0,\"region\":{\"x\":3,\"y\":13}},{\"count\":2,\"region\":{\"x\":3,\"y\":14}},{\"count\":0,\"region\":{\"x\":4,\"y\":10}},{\"count\":1,\"region\":{\"x\":4,\"y\":14}},{\"count\":1,\"region\":{\"x\":5,\"y\":14}},{\"count\":1,\"region\":{\"x\":6,\"y\":14}},{\"count\":2,\"region\":{\"x\":7,\"y\":11}},{\"count\":0,\"region\":{\"x\":7,\"y\":12}},{\"count\":0,\"region\":{\"x\":7,\"y\":13}},{\"count\":0,\"region\":{\"x\":7,\"y\":14}}],\"movements\":[{\"count\":0,\"direction\":\"DOWN\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":3,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":3,\"y\":14}},{\"count\":5,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":4,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":11}}]}'\n" +
                "Hero H@59fdaa77 of player P@76fd46ad received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":14,\"y\":13}},{\"count\":1,\"region\":{\"x\":13,\"y\":12}},{\"count\":1,\"region\":{\"x\":14,\"y\":12}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":12,\"y\":15}},{\"count\":1,\"region\":{\"x\":13,\"y\":15}},{\"count\":1,\"region\":{\"x\":14,\"y\":15}},{\"count\":1,\"region\":{\"x\":15,\"y\":15}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":15,\"y\":15}},{\"count\":8,\"direction\":\"UP\",\"region\":{\"x\":11,\"y\":11}}]}'\n" +
                "Hero H@149c14b4 of player P@310933ee received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"region\":{\"x\":12,\"y\":7}},{\"count\":1,\"region\":{\"x\":16,\"y\":6}},{\"count\":1,\"region\":{\"x\":16,\"y\":9}},{\"count\":1,\"region\":{\"x\":12,\"y\":5}},{\"count\":1,\"region\":{\"x\":16,\"y\":7}},{\"count\":1,\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"region\":{\"x\":12,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":5}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":9}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":7}}]}'\n" +
                "Hero H@5bc68d76 of player P@4fe98a9c received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":5,\"y\":8}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":4}},{\"count\":1,\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"region\":{\"x\":4,\"y\":4}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":8,\"y\":6}},{\"count\":0,\"region\":{\"x\":6,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":6,\"y\":4}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":8,\"y\":6}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":7,\"y\":7}},{\"count\":8,\"direction\":\"LEFT\",\"region\":{\"x\":8,\"y\":8}}]}'\n" +
                "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#009001001-=#-=#-=#-=#-=#-=#-=#-=#-=#002006001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#002002002002-=#-=#-=#-=#-=#-=#-=#-=#00100100100A-=#-=#-=#001001001001002-=#-=#-=#-=#-=#-=#-=#-=#001001003001-=#-=#-=#002001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"-------------------------------------------------------------------------------------------♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦--------♥♥♥♥♥---♦♦♦---------♥♥♥♥--------------------------♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣-------♠♠♠---------------------------------------------------------------------------------------------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
                "--------------------------------------------------------------\n" +
                "Hero H@14fa45c2 of player P@53ff5eb9 received command:'{\"increase\":[{\"count\":4,\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"region\":{\"x\":2,\"y\":10}},{\"count\":0,\"region\":{\"x\":2,\"y\":11}},{\"count\":0,\"region\":{\"x\":2,\"y\":12}},{\"count\":0,\"region\":{\"x\":3,\"y\":9}},{\"count\":1,\"region\":{\"x\":3,\"y\":15}},{\"count\":1,\"region\":{\"x\":4,\"y\":15}},{\"count\":1,\"region\":{\"x\":5,\"y\":15}},{\"count\":1,\"region\":{\"x\":6,\"y\":15}},{\"count\":1,\"region\":{\"x\":7,\"y\":12}},{\"count\":1,\"region\":{\"x\":7,\"y\":13}},{\"count\":1,\"region\":{\"x\":7,\"y\":14}},{\"count\":0,\"region\":{\"x\":7,\"y\":15}},{\"count\":0,\"region\":{\"x\":8,\"y\":12}}],\"movements\":[{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":2,\"y\":9}},{\"count\":0,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":2,\"y\":10}},{\"count\":2,\"direction\":\"DOWN\",\"region\":{\"x\":3,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":3,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":14}}]}'\n" +
                "Hero H@59fdaa77 of player P@76fd46ad received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":15,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":14}},{\"count\":1,\"region\":{\"x\":15,\"y\":14}},{\"count\":1,\"region\":{\"x\":15,\"y\":13}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":11,\"y\":16}},{\"count\":1,\"region\":{\"x\":12,\"y\":16}},{\"count\":2,\"region\":{\"x\":15,\"y\":11}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":15}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":11,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":16}},{\"count\":8,\"direction\":\"LEFT_UP\",\"region\":{\"x\":11,\"y\":12}}]}'\n" +
                "Hero H@149c14b4 of player P@310933ee received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":13,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"region\":{\"x\":17,\"y\":9}},{\"count\":1,\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"region\":{\"x\":17,\"y\":7}},{\"count\":1,\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"region\":{\"x\":11,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"region\":{\"x\":12,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":4}},{\"count\":1,\"region\":{\"x\":17,\"y\":10}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":16,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":17,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":12,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":12,\"y\":8}}]}'\n" +
                "Hero H@5bc68d76 of player P@4fe98a9c received command:'{\"increase\":[{\"count\":1,\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"region\":{\"x\":4,\"y\":8}},{\"count\":1,\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"region\":{\"x\":4,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"region\":{\"x\":8,\"y\":4}},{\"count\":1,\"region\":{\"x\":3,\"y\":5}},{\"count\":1,\"region\":{\"x\":4,\"y\":6}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":2,\"region\":{\"x\":4,\"y\":8}},{\"count\":0,\"region\":{\"x\":4,\"y\":7}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":8}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":8,\"y\":4}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":6,\"y\":7}},{\"count\":8,\"direction\":\"LEFT\",\"region\":{\"x\":7,\"y\":8}}]}'\n" +
                "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#001001001001001001001-=#-=#-=#-=#-=#-=#001001001001001-=#-=#001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#009001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#001001001001001-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#002002-=#-=#-=#-=#001005-=#-=#-=#-=#-=#-=#-=#-=#-=#001001002001001-=#-=#-=#-=#-=#-=#001001001009002-=#-=#001002001001001001002-=#-=#-=#-=#-=#-=#001001003001001-=#-=#001001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001-=#001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001001-=#001001001-=#-=#001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"----------------------------------------------------------------------♦♦♦♦♦♦-------♥♥♥♥♥--♦♦♦♦♦♦♦------♥♥♥♥♥--♦♦♦♦♦♦------♥♥♥♥♥♥---♦♦♦♦♦------♥♥♥♥♥♥♥--♦♦♦♦♦------♥♥♥♥♥♥♥--♦♦♦♦♦------♥♥♥♥♥---------♣♣----♥♥---------♣♣♣♣♣------♠♠♠♠♠--♣♣♣♣♣♣♣------♠♠♠♠♠--♣♣♣♣♣♣♣------♠♠♠♠♠♠-♣♣♣♣♣♣------♠♠♠♠♠♠♠--♣♣♣♣♣-------♠♠♠♠♠♠-♣♣♣--♣----------♠------------------------------------------------------------------------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
                "--------------------------------------------------------------\n";

        String replayName = saveToFile(data);

        String playerName = "P@53ff5eb9";
        LoggerReader loggerReader = new LoggerReaderImpl(replayName, playerName);

        assertEquals(4, loggerReader.size());

        // when then
        int tick = 0;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"-------------------------------------------------------------------------------------------------------------------------------------♦-----------♥------------------------------------------------------------------------------------------------------------♣-----------♠-------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":5,\"y\":12},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":50,\"rounds\":50,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":5,\"y\":12}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":5,\"y\":12}},{\"count\":7,\"direction\":\"DOWN\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":5,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":5,\"y\":12}},{\"count\":6,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":12}}]}, " +
                "demo2@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":13,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":13}},{\"count\":11,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":13}}]}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":14,\"y\":7}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"LEFT_UP\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"UP\",\"region\":{\"x\":14,\"y\":7}},{\"count\":3,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":7}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":7}}]}, " +
                "demo4@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":6}},{\"count\":2,\"region\":{\"x\":6,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":6,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":9,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 1;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#00C001001-=#-=#-=#-=#-=#-=#-=#-=#-=#006007001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#002003002-=#-=#-=#-=#-=#-=#-=#-=#-=#00100100A-=#-=#-=#-=#-=#002001002-=#-=#-=#-=#-=#-=#-=#-=#-=#001003001-=#-=#-=#-=#-=#003002003-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"----------------------------------------------------------------------------------------------------------------♦♦♦---------♥♥♥-----♦♦♦---------♥♥♥-----♦♦♦---------♥♥♥------------------------------------------------------------------♣♣♣---------♠♠♠-----♣♣♣---------♠♠♠-----♣♣♣---------♠♠♠----------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":5,\"y\":12},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":49,\"rounds\":50,\"showName\":true,\"tick\":1}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"region\":{\"x\":4,\"y\":12}},{\"count\":3,\"region\":{\"x\":4,\"y\":13}},{\"count\":0,\"region\":{\"x\":5,\"y\":11}},{\"count\":1,\"region\":{\"x\":5,\"y\":13}},{\"count\":2,\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"region\":{\"x\":6,\"y\":12}},{\"count\":1,\"region\":{\"x\":6,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":11}},{\"count\":2,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":4,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":5,\"y\":11}},{\"count\":5,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":13}}]}, " +
                "demo2@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"region\":{\"x\":13,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"region\":{\"x\":12,\"y\":13}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":14}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":13}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":12,\"y\":12}},{\"count\":8,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":12}}]}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":2,\"region\":{\"x\":13,\"y\":6}},{\"count\":2,\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"region\":{\"x\":15,\"y\":8}},{\"count\":1,\"region\":{\"x\":15,\"y\":7}},{\"count\":1,\"region\":{\"x\":13,\"y\":8}},{\"count\":1,\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"region\":{\"x\":13,\"y\":7}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":13,\"y\":8}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":8}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":13,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":6}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":13,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":14,\"y\":8}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":13,\"y\":6}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":14,\"y\":8}}]}, " +
                "demo4@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":6,\"y\":5}},{\"count\":0,\"region\":{\"x\":5,\"y\":5}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":7,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":6,\"y\":5}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":6}},{\"count\":9,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":7}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 2;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#009001001-=#-=#-=#-=#-=#-=#-=#-=#-=#002006001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#002002002002-=#-=#-=#-=#-=#-=#-=#-=#00100100100A-=#-=#-=#001001001001002-=#-=#-=#-=#-=#-=#-=#-=#001001003001-=#-=#-=#002001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#-=#001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"-------------------------------------------------------------------------------------------♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦♦-------♥♥♥♥♥---♦♦♦♦--------♥♥♥♥♥---♦♦♦---------♥♥♥♥--------------------------♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣--------♠♠♠♠---♣♣♣♣♣-------♠♠♠---------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":5,\"y\":12},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":48,\"rounds\":50,\"showName\":true,\"tick\":2}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":2,\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"region\":{\"x\":3,\"y\":11}},{\"count\":1,\"region\":{\"x\":3,\"y\":12}},{\"count\":0,\"region\":{\"x\":3,\"y\":13}},{\"count\":2,\"region\":{\"x\":3,\"y\":14}},{\"count\":0,\"region\":{\"x\":4,\"y\":10}},{\"count\":1,\"region\":{\"x\":4,\"y\":14}},{\"count\":1,\"region\":{\"x\":5,\"y\":14}},{\"count\":1,\"region\":{\"x\":6,\"y\":14}},{\"count\":2,\"region\":{\"x\":7,\"y\":11}},{\"count\":0,\"region\":{\"x\":7,\"y\":12}},{\"count\":0,\"region\":{\"x\":7,\"y\":13}},{\"count\":0,\"region\":{\"x\":7,\"y\":14}}],\"movements\":[{\"count\":0,\"direction\":\"DOWN\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":3,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":11}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":12}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":3,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":3,\"y\":14}},{\"count\":5,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":4,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":7,\"y\":11}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":11}}]}, " +
                "demo2@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":14,\"y\":13}},{\"count\":1,\"region\":{\"x\":13,\"y\":12}},{\"count\":1,\"region\":{\"x\":14,\"y\":12}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"region\":{\"x\":12,\"y\":15}},{\"count\":1,\"region\":{\"x\":13,\"y\":15}},{\"count\":1,\"region\":{\"x\":14,\"y\":15}},{\"count\":1,\"region\":{\"x\":15,\"y\":15}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":12}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":13,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":14,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":15,\"y\":15}},{\"count\":8,\"direction\":\"UP\",\"region\":{\"x\":11,\"y\":11}}]}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"region\":{\"x\":12,\"y\":7}},{\"count\":1,\"region\":{\"x\":16,\"y\":6}},{\"count\":1,\"region\":{\"x\":16,\"y\":9}},{\"count\":1,\"region\":{\"x\":12,\"y\":5}},{\"count\":1,\"region\":{\"x\":16,\"y\":7}},{\"count\":1,\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"region\":{\"x\":12,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":5}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":12,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":14,\"y\":9}},{\"count\":2,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":7}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":16,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":6}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":12,\"y\":7}}]}, " +
                "demo4@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":5,\"y\":8}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"region\":{\"x\":5,\"y\":6}},{\"count\":1,\"region\":{\"x\":6,\"y\":4}},{\"count\":1,\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"region\":{\"x\":4,\"y\":4}},{\"count\":1,\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"region\":{\"x\":8,\"y\":6}},{\"count\":0,\"region\":{\"x\":6,\"y\":6}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":7}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":8,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":6}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":6,\"y\":4}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":7,\"y\":5}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":4,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":5,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":8,\"y\":6}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":7,\"y\":7}},{\"count\":8,\"direction\":\"LEFT\",\"region\":{\"x\":8,\"y\":8}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 3;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001-=#-=#001001001001001001001-=#-=#-=#-=#-=#-=#001001001001001-=#-=#001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#009001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#001001001001001-=#-=#-=#-=#-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#-=#-=#002002-=#-=#-=#-=#001005-=#-=#-=#-=#-=#-=#-=#-=#-=#001001002001001-=#-=#-=#-=#-=#-=#001001001009002-=#-=#001002001001001001002-=#-=#-=#-=#-=#-=#001001003001001-=#-=#001001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001-=#001001001001001001-=#-=#-=#-=#-=#-=#001001001001001001001-=#-=#001001001001001-=#-=#-=#-=#-=#-=#-=#001001001001001001-=#001001001-=#-=#001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#001-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"       ╔════┐            ╔═╝....╚═┐        ╔═╝........╚═┐     ╔╝............╚┐    ║......B.......│   ╔╝......B.......╚┐  ║.......B...2....│ ╔╝...1...BB.......╚┐║.......$OB$.......│║......BBOOOBBBB...│║...BBBBOOOBB......│║.......$BO$.......│└╗.......BB...3...┌┘ ║....4...B.......│  └╗.......B......┌┘   ║.......B......│    └╗............┌┘     └─╗........┌─┘        └─╗....┌─┘            └────┘       \",\"----------------------------------------------------------------------♦♦♦♦♦♦-------♥♥♥♥♥--♦♦♦♦♦♦♦------♥♥♥♥♥--♦♦♦♦♦♦------♥♥♥♥♥♥---♦♦♦♦♦------♥♥♥♥♥♥♥--♦♦♦♦♦------♥♥♥♥♥♥♥--♦♦♦♦♦------♥♥♥♥♥---------♣♣----♥♥---------♣♣♣♣♣------♠♠♠♠♠--♣♣♣♣♣♣♣------♠♠♠♠♠--♣♣♣♣♣♣♣------♠♠♠♠♠♠-♣♣♣♣♣♣------♠♠♠♠♠♠♠--♣♣♣♣♣-------♠♠♠♠♠♠-♣♣♣--♣----------♠------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":5,\"y\":12},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":47,\"rounds\":50,\"showName\":true,\"tick\":3}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":4,\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"region\":{\"x\":2,\"y\":10}},{\"count\":0,\"region\":{\"x\":2,\"y\":11}},{\"count\":0,\"region\":{\"x\":2,\"y\":12}},{\"count\":0,\"region\":{\"x\":3,\"y\":9}},{\"count\":1,\"region\":{\"x\":3,\"y\":15}},{\"count\":1,\"region\":{\"x\":4,\"y\":15}},{\"count\":1,\"region\":{\"x\":5,\"y\":15}},{\"count\":1,\"region\":{\"x\":6,\"y\":15}},{\"count\":1,\"region\":{\"x\":7,\"y\":12}},{\"count\":1,\"region\":{\"x\":7,\"y\":13}},{\"count\":1,\"region\":{\"x\":7,\"y\":14}},{\"count\":0,\"region\":{\"x\":7,\"y\":15}},{\"count\":0,\"region\":{\"x\":8,\"y\":12}}],\"movements\":[{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":2,\"y\":9}},{\"count\":0,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":2,\"y\":9}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":2,\"y\":10}},{\"count\":2,\"direction\":\"DOWN\",\"region\":{\"x\":3,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":3,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":4,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":5,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":6,\"y\":15}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":12}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":13}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":7,\"y\":14}}]}, " +
                "demo2@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":15,\"y\":15}},{\"count\":1,\"region\":{\"x\":11,\"y\":14}},{\"count\":1,\"region\":{\"x\":15,\"y\":14}},{\"count\":1,\"region\":{\"x\":15,\"y\":13}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"region\":{\"x\":11,\"y\":16}},{\"count\":1,\"region\":{\"x\":12,\"y\":16}},{\"count\":2,\"region\":{\"x\":15,\"y\":11}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":15}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":14}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":15,\"y\":13}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":10,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":11,\"y\":16}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":12,\"y\":16}},{\"count\":8,\"direction\":\"LEFT_UP\",\"region\":{\"x\":11,\"y\":12}}]}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":13,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"region\":{\"x\":17,\"y\":9}},{\"count\":1,\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"region\":{\"x\":17,\"y\":7}},{\"count\":1,\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"region\":{\"x\":11,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"region\":{\"x\":12,\"y\":4}},{\"count\":1,\"region\":{\"x\":16,\"y\":4}},{\"count\":1,\"region\":{\"x\":17,\"y\":10}}],\"movements\":[{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":16,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":17,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":15,\"y\":9}},{\"count\":1,\"direction\":\"UP\",\"region\":{\"x\":16,\"y\":10}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":14,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":9}},{\"count\":1,\"direction\":\"RIGHT\",\"region\":{\"x\":17,\"y\":8}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":12,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":16,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_UP\",\"region\":{\"x\":17,\"y\":10}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":11,\"y\":4}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":13,\"y\":5}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":12,\"y\":8}}]}, " +
                "demo4@codenjoy.com={\"increase\":[{\"count\":1,\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"region\":{\"x\":4,\"y\":8}},{\"count\":1,\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"region\":{\"x\":4,\"y\":7}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"region\":{\"x\":8,\"y\":4}},{\"count\":1,\"region\":{\"x\":3,\"y\":5}},{\"count\":1,\"region\":{\"x\":4,\"y\":6}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"region\":{\"x\":7,\"y\":3}},{\"count\":2,\"region\":{\"x\":4,\"y\":8}},{\"count\":0,\"region\":{\"x\":4,\"y\":7}}],\"movements\":[{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":8}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":9,\"y\":4}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":7}},{\"count\":1,\"direction\":\"RIGHT_DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":8,\"y\":4}},{\"count\":1,\"direction\":\"LEFT_UP\",\"region\":{\"x\":3,\"y\":5}},{\"count\":1,\"direction\":\"LEFT\",\"region\":{\"x\":4,\"y\":6}},{\"count\":1,\"direction\":\"DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":1,\"direction\":\"LEFT_DOWN\",\"region\":{\"x\":7,\"y\":3}},{\"count\":2,\"direction\":\"LEFT\",\"region\":{\"x\":6,\"y\":7}},{\"count\":8,\"direction\":\"LEFT\",\"region\":{\"x\":7,\"y\":8}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 4; // out of
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":true,\"layers\":[\"" + REPLAY + "\",\"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":-1,\"y\":-1},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":-1,\"rounds\":-1,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 5; // out of
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":true,\"layers\":[\"" + REPLAY + "\",\"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":-1,\"y\":-1},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":-1,\"rounds\":-1,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[]", toString(loggerReader.getAllLastActions(tick)));
    }

    private long unique() {
        return Calendar.getInstance().getTimeInMillis();
    }

    String data = "Game started\n" +
            "New player P@6c3f5566 registered with hero H@12405818 with base at '{\"x\":1,\"y\":2}' and color '0' for user 'demo1@codenjoy.com'\n" +
            "// Please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo1@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@6c3f5566'}\"\n" +

            "New player P@314c508a registered with hero H@10b48321 with base at '{\"x\":3,\"y\":2}' and color '1' for user 'demo2@codenjoy.com'\n" +
            "// Please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo2@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@314c508a'}\"\n" +

            "New player P@6b67034 registered with hero H@16267862 with base at '{\"x\":2,\"y\":1}' and color '2' for user 'demo3@codenjoy.com'\n" +
            "// Please run \"http://127.0.0.1:8080/codenjoy-contest/admin31415?player=demo3@codenjoy.com&gameName=expansion&data={'startFromTick':0,'replayName':'game-E@6a396c1e-1','playerName':'P@6b67034'}\"\n" +

            "Hero H@12405818 of player P@6c3f5566 received command:'{}'\n" +
            "Hero H@10b48321 of player P@314c508a received command:'{}'\n" +
            "Hero H@16267862 of player P@6b67034 received command:'{}'\n" +
            "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥-♦---♣-------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
            "--------------------------------------------------------------\n" +
            "Hero H@12405818 of player P@6c3f5566 received command:'{\"increase\":[{\"count\":10,\"region\":{\"x\":1,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":1,\"y\":2}}]}'\n" +
            "Hero H@10b48321 of player P@314c508a received command:'{}'\n" +
            "Hero H@16267862 of player P@6b67034 received command:'{}'\n" +
            "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥♦---♣-------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
            "--------------------------------------------------------------\n" +
            "Hero H@12405818 of player P@6c3f5566 received command:'{\"increase\":[{\"count\":10,\"region\":{\"x\":2,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":2}}]}'\n" +
            "Hero H@10b48321 of player P@314c508a received command:'{}'\n" +
            "Hero H@16267862 of player P@6b67034 received command:'{}'\n" +
            "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
            "--------------------------------------------------------------\n" +
            "Hero H@12405818 of player P@6c3f5566 received command:'{}'\n" +
            "Hero H@10b48321 of player P@314c508a is not alive\n" +
            "Hero H@10b48321 of player P@314c508a received command:'{}'\n" +
            "Hero H@16267862 of player P@6b67034 received command:'{}'\n" +
            "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
            "--------------------------------------------------------------\n" +
            "Hero H@12405818 of player P@6c3f5566 received command:'{}'\n" +
            "Hero H@10b48321 of player P@314c508a is not alive\n" +
            "Hero H@10b48321 of player P@314c508a received command:'{}'\n" +
            "Hero H@16267862 of player P@6b67034 received command:'{\"increase\":[{\"count\":2,\"region\":{\"x\":2,\"y\":1}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":1}}]}'\n" +
            "Board:'{\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A002-=#-=#-=#-=#-=#-=#\",\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣♣------\"],\"offset\":{\"x\":0,\"y\":0}}'\n" +
            "--------------------------------------------------------------";

    @Test
    public void testParseFileWhenHeroIsNotAlive_forDiedUser() throws IOException {
        // given
        SettingsWrapper.setup().roundTicks(50);

        String replayName = saveToFile(data);

        String playerName = "P@314c508a";
        LoggerReader loggerReader = new LoggerReaderImpl(replayName, playerName);

        assertEquals(5, loggerReader.size());

        // when then
        int tick = 0;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥-♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":3,\"y\":2},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":50,\"rounds\":50,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 1;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":3,\"y\":2},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":49,\"rounds\":50,\"showName\":true,\"tick\":1}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":1,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":1,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 2;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":3,\"y\":2},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":48,\"rounds\":50,\"showName\":true,\"tick\":2}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":2,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 3;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":3,\"y\":2},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":47,\"rounds\":50,\"showName\":true,\"tick\":3}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 4;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A002-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣♣------\"],\"levelProgress\":{},\"myBase\":{\"x\":3,\"y\":2},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":46,\"rounds\":50,\"showName\":true,\"tick\":4}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":2,\"region\":{\"x\":2,\"y\":1}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":1}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 5; // out of
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":true,\"layers\":[\"                                           OOO  OOOO OOO       O  O O    O  O      O  O O    O  O      OOO  OOO  OOO       OO   O    O         O O  O    O         O  O OOOO O                                                  O     OO  O  O      O    O  O O  O      O    O  O O  O      O    OOOO  OOO      O    O  O    O      O    O  O   O       OOOO O  O OO                                            \",\"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":-1,\"y\":-1},\"myColor\":1,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":-1,\"rounds\":-1,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[]", toString(loggerReader.getAllLastActions(tick)));
    }

    @Test
    public void testParseFileWhenHeroIsNotAlive_forAttackerUser() throws IOException {
        // given
        SettingsWrapper.setup().roundTicks(50);

        String replayName = saveToFile(data);

        String playerName = "P@6c3f5566";
        LoggerReader loggerReader = new LoggerReaderImpl(replayName, playerName);

        assertEquals(5, loggerReader.size());

        // when then
        int tick = 0;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥-♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":1,\"y\":2},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":50,\"rounds\":50,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 1;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":1,\"y\":2},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":49,\"rounds\":50,\"showName\":true,\"tick\":1}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":1,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":1,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 2;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":1,\"y\":2},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":48,\"rounds\":50,\"showName\":true,\"tick\":2}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":2,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 3;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":1,\"y\":2},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":47,\"rounds\":50,\"showName\":true,\"tick\":3}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 4;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A002-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣♣------\"],\"levelProgress\":{},\"myBase\":{\"x\":1,\"y\":2},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":46,\"rounds\":50,\"showName\":true,\"tick\":4}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":2,\"region\":{\"x\":2,\"y\":1}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":1}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 5; // out of
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":true,\"layers\":[\"                                           OOO  OOOO OOO       O  O O    O  O      O  O O    O  O      OOO  OOO  OOO       OO   O    O         O O  O    O         O  O OOOO O                                                  O     OO  O  O      O    O  O O  O      O    O  O O  O      O    OOOO  OOO      O    O  O    O      O    O  O   O       OOOO O  O OO                                            \",\"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":-1,\"y\":-1},\"myColor\":0,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":-1,\"rounds\":-1,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[]", toString(loggerReader.getAllLastActions(tick)));
    }

    @Test
    public void testParseFileWhenHeroIsNotAlive_forNeutralUser() throws IOException {
        // given
        SettingsWrapper.setup().roundTicks(50);

        String replayName = saveToFile(data);

        String playerName = "P@6b67034";
        LoggerReader loggerReader = new LoggerReaderImpl(replayName, playerName);

        assertEquals(5, loggerReader.size());

        // when then
        int tick = 0;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A-=#00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥-♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":2,\"y\":1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":50,\"rounds\":50,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 1;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A00A-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥♦---♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":2,\"y\":1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":49,\"rounds\":50,\"showName\":true,\"tick\":1}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":1,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":1,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 2;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":2,\"y\":1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":48,\"rounds\":50,\"showName\":true,\"tick\":2}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={\"increase\":[{\"count\":10,\"region\":{\"x\":2,\"y\":2}}],\"movements\":[{\"count\":10,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":2}}]}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 3;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣-------\"],\"levelProgress\":{},\"myBase\":{\"x\":2,\"y\":1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":47,\"rounds\":50,\"showName\":true,\"tick\":3}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 4;
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#00A00A-=#-=#-=#-=#00A002-=#-=#-=#-=#-=#-=#\",\"inLobby\":false,\"layers\":[\"╔═══┐║...│║1.2│║.3.│└───┘\",\"-----------♥♥----♣♣------\"],\"levelProgress\":{},\"myBase\":{\"x\":2,\"y\":1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":46,\"rounds\":50,\"showName\":true,\"tick\":4}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[demo1@codenjoy.com={}, " +
                "demo2@codenjoy.com={}, " +
                "demo3@codenjoy.com={\"increase\":[{\"count\":2,\"region\":{\"x\":2,\"y\":1}}],\"movements\":[{\"count\":2,\"direction\":\"RIGHT\",\"region\":{\"x\":2,\"y\":1}}]}]", toString(loggerReader.getAllLastActions(tick)));

        // when then
        tick = 5; // out of
        assertEquals("{\"available\":0,\"forces\":\"-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#-=#\",\"inLobby\":true,\"layers\":[\"                                           OOO  OOOO OOO       O  O O    O  O      O  O O    O  O      OOO  OOO  OOO       OO   O    O         O O  O    O         O  O OOOO O                                                  O     OO  O  O      O    O  O O  O      O    O  O O  O      O    OOOO  OOO      O    O  O    O      O    O  O   O       OOOO O  O OO                                            \",\"----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\"],\"levelProgress\":{},\"myBase\":{\"x\":-1,\"y\":-1},\"myColor\":2,\"offset\":{\"x\":0,\"y\":0},\"onlyMyName\":false,\"round\":-1,\"rounds\":-1,\"showName\":true,\"tick\":0}", JsonUtils.toStringSorted(loggerReader.getBoard(tick)));
        assertEquals("[]", toString(loggerReader.getAllLastActions(tick)));
    }

    private String toString(Map<String, JSONObject> allLastActions) {
        return allLastActions.entrySet().stream()
                .map(entry -> new HashMap.SimpleEntry<>(
                        entry.getKey(),
                        JsonUtils.toStringSorted(entry.getValue())))
                .collect(toList()).toString();
    }

    private String saveToFile(String data) throws IOException {
        String replayName = "testReplay-" + unique();
        File file = new File("gameData" + SEP + replayName + ".txt");
        file.getParentFile().mkdirs();
        file.createNewFile();

        FileOutputStream fos = new FileOutputStream(file);
        BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(fos, StandardCharsets.UTF_8));

        List<String> lines = Arrays.asList(data.split("\n"));

        for (String line : lines) {
            writer.write(line);
            writer.newLine();
        }
        writer.flush();
        writer.close();

        return replayName;
    }

}