using System.ComponentModel;

namespace SnakeBattle.Enums
{
    public enum CellType
    {
        [Description(" ")] None,
        [Description("☼")] Wall,
        [Description("#")] StartFloor,
        [Description("○")] Apple,
        [Description("●")] Stone,
        [Description("©")] FlyingPill,
        [Description("®")] FuryPill,
        [Description("$")] Gold,
        [Description("▼")] HeadDown,
        [Description("◄")] HeadLeft,
        [Description("►")] HeadRight,
        [Description("▲")] HeadUp,
        [Description("☻")] HeadDead,
        [Description("♥")] HeadEvil,
        [Description("♠")] HeadFly,
        [Description("&")] HeadSleep,
        [Description("╙")] TailEndDown,
        [Description("╘")] TailEndLeft,
        [Description("╓")] TailEndUp,
        [Description("╕")] TailEndRight,
        [Description("~")] TailInactive,
        [Description("═")] BodyHorizontal,
        [Description("║")] BodyVertical,
        [Description("╗")] BodyLeftDown,
        [Description("╝")] BodyLeftUp,
        [Description("╔")] BodyRightDown,
        [Description("╚")] BodyRightUp,
        [Description("˅")] EnemyHeadDown,
        [Description("<")] EnemyHeadLeft,
        [Description(">")] EnemyHeadRight,
        [Description("˄")] EnemyHeadUp,
        [Description("☺")] EnemyHeadDead,
        [Description("♣")] EnemyHeadEvil,
        [Description("♦")] EnemyHeadFly,
        [Description("ø")] EnemyHeadSleep,
        [Description("¤")] EnemyTailEndDown,
        [Description("×")] EnemyTailEndLeft,
        [Description("æ")] EnemyTailEndUp,
        [Description("ö")] EnemyTailEndRight,
        [Description("*")] EnemyTailInactive,
        [Description("─")] EnemyBodyHorizontal,
        [Description("|")] EnemyBodyVertical,
        [Description("┐")] EnemyBodyLeftDown,
        [Description("┘")] EnemyBodyLeftUp,
        [Description("┌")] EnemyBodyRightDown,
        [Description("└")] EnemyBodyRightUp,
        [Description("?")] Unknown
    }
}