package com.codenjoy.dojo.battlecity.model;

/**
 * User: sanja
 * Date: 06.06.13
 * Time: 17:38
 */
public enum Elements {

    GROUND(' '),
    WALL('☼'),

    CONSTRUCTION('╬'),

    CONSTRUCTION_DESTROYED_DOWN('╩'),
    CONSTRUCTION_DESTROYED_DOWN_TWICE('╨'),

    CONSTRUCTION_DESTROYED_UP('╦'),
    CONSTRUCTION_DESTROYED_UP_TWICE('╥'),

    CONSTRUCTION_DESTROYED_LEFT('╠'),
    CONSTRUCTION_DESTROYED_LEFT_TWICE('╞'),

    CONSTRUCTION_DESTROYED_RIGHT('╣'),
    CONSTRUCTION_DESTROYED_RIGHT_TWICE('╡'),

    CONSTRUCTION_DESTROYED_LEFT_RIGHT('│'),
    CONSTRUCTION_DESTROYED_UP_DOWN('─'),

    CONSTRUCTION_DESTROYED_UP_LEFT('╒'),
    CONSTRUCTION_DESTROYED_LEFT_UP('╓'),

    CONSTRUCTION_DESTROYED_RIGHT_UP('╖'),
    CONSTRUCTION_DESTROYED_UP_RIGHT('╕'),

    CONSTRUCTION_DESTROYED_DOWN_LEFT('╘'),
    CONSTRUCTION_DESTROYED_LEFT_DOWN('╙'),

    CONSTRUCTION_DESTROYED_DOWN_RIGHT('╛'),
    CONSTRUCTION_DESTROYED_RIGHT_DOWN('╜'),

    BULLET('•'),
    TANK_UP('▲'),
    TANK_RIGHT('►'),
    TANK_DOWN('▼'),
    TANK_LEFT('◄');

    char ch;

    Elements(char ch) {
        this.ch = ch;
    }

}
